POST http://localhost:3000/create/custom_stub
Content-Type: application/json

{
  "port": 4600,
  "protocol": "http",
  "defaultResponse": {
    "statusCode": 200,
    "body": "charro",
    "headers": {
      "trace-id": "{{$uuid}}"
    }
  }
}

###

GET http://localhost:3000/custom_stub
Accept: application/json

###
